//
//  HomeViewController.swift
//  NewsFeed
//
//  Created yana mulyana on 10/02/20.
//  Copyright © 2020 LinkAJa. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class HomeViewController: UIViewController {

    var presenter: HomeViewToPresenterProtocol?
    
	override func viewDidLoad() {
        super.viewDidLoad()
        self.presenter?.fetchData()
    }

}

extension HomeViewController: HomePresenterToViewProtocol {
    func showData() {
        //do something & add parameter data
    }
    
    func showError(errorName: String) {
        //showAlert(errorName: errorName, statusCode: statusCode)
    }
    
    func hideHud() {
        
    }
}
