//
//  HomePresenter.swift
//  NewsFeed
//
//  Created yana mulyana on 10/02/20.
//  Copyright © 2020 LinkAJa. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

class HomePresenter: HomeViewToPresenterProtocol {

    var view: HomePresenterToViewProtocol?
    var interactor: HomePresenterToInteractorProtocol?
    var router: HomePresenterToRouterProcotol?
    
    func fetchData() {
        interactor?.fetchData()
    }
    
    func routeToDetail(navigation: UINavigationController) {
        router?.toDetail(navigation: navigation)
    }

}

extension HomePresenter: HomeInteractorToPresenterProtocol{
    func dataFetched(object: Feed) {
        view?.showData()
    }
    
    func dataFetchedFailed(errorName: String) {
        view?.showError(errorName: errorName)
    }
    
    func viewLoading() {
        view?.hideHud()
    }
}
