//
//  HomeProtocols.swift
//  NewsFeed
//
//  Created yana mulyana on 10/02/20.
//  Copyright © 2020 LinkAJa. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

//MARK: Presenter - Router
protocol HomePresenterToRouterProcotol: class {
    static func createModule() -> UIViewController
    func toDetail(navigation: UINavigationController)
}

//MARK: View - Presenter
protocol HomeViewToPresenterProtocol: class {
    var view: HomePresenterToViewProtocol? {get set}
    var interactor: HomePresenterToInteractorProtocol? {get set}
    var router: HomePresenterToRouterProcotol? {get set}
    
    func fetchData()
    func routeToDetail(navigation: UINavigationController)
}

//MARK: Presenter - View
protocol HomePresenterToViewProtocol {
    func showData()
    func showError(errorName: String)
    func hideHud()
}

//MARK: Presenter - Interactor
protocol HomePresenterToInteractorProtocol {
    var presenter: HomeInteractorToPresenterProtocol? {get set}
    func fetchData()
}

//MARK: Interactor - Presenter
protocol HomeInteractorToPresenterProtocol: class {
    func dataFetched(object: Feed)
    func dataFetchedFailed(errorName: String)
    func viewLoading()
}

